apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: schweigl
spec:
  #  entryPoints:
  #    - websecure
  routes:
    - kind: Rule
      match: Host(`schweigl.cloud.key.fit`)
      services:
        - name: appsrv
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appsrv

spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    component: appsrv


#  tls:
#    secretName: default-ingress-cert
